jwt.secret=
jwt.expiration=720

app.host=http://localhost:8082
app.redirect_uri=/redirect?u=%s&k=%s&type=verify_email
app.redirect_uri.verify_account=/redirect?u=%s&k=%s&type=verify_account
app.redirect_uri.support=/redirect?type=contact-support
app.redirect_uri.email=/redirect?u=%s&type=%s
app.redirect_uri.google=/redirect?code=%s&type=google

user.verification.expire=60

