google.app.id=
google.app.secret=
google.redirect.uri=http://localhost:8082/fs/api/v1/auth/login-google
google.link.get.token=https://accounts.google.com/o/oauth2/token
google.link.get.user_info=https://www.googleapis.com/oauth2/v1/userinfo?access_token=
